  protonmail-webhook:
    environment:
#     debug: "true"
     selfsigned: true
     mail_to: 
     mail_host: 
     mail_port: 
     mail_user: 
     mail_pass: 
     sitename: 
    image: protonmail-webhook:latest
    container_name: webhook
    restart: unless-stopped
    ports:
     - 8080:8080
    networks:
     - mail
     - web
    depends_on:
      - protonmail
    logging:
      options:
        max-size: "1m"
        max-file: "10"
